'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {departments,istDate,type Policy} from '@/lib/workforce-rules';
import {tripUi} from '@/lib/travel-modes';
import type {Profile,Entry} from '@/lib/workforce-store';
import {canReview} from '@/lib/permissions';
import type {User} from '@/lib/auth';
type Data={people:User[];profiles:(Partial<Profile>&{employee:string})[];policy:Policy;entries:Entry[];payrollAccess:boolean;audit:{actor:string;action:string;target:string;details:string;created:number}[];sync:null|{configured:boolean;alert?:{tab:string;message:string;detected:number};status:string;error?:string;finished?:number}};
const currentDate=()=>istDate();
function gps():Promise<{lat:number;lng:number;accuracy:number;time:number}>{return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('Location is unavailable on this device.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,time:p.timestamp}),()=>reject(Error('Location failed. Allow precise location permission and try again, or request an exception.')),{enableHighAccuracy:true,maximumAge:0,timeout:20000});});}
export default function WorkforcePanel({me}:{me:User}){
 const [data,setData]=useState<Data|null>(null),[section,setSection]=useState('My day'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[chosen,setChosen]=useState('');
 const load=useCallback(async()=>{const r=await fetch('/api/workforce');const d=await r.json() as Data & {error?:string};if(!r.ok)throw Error(d.error);setData(d);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 async function act(body:Record<string,unknown>){setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/workforce',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await load();setSuccess('Saved successfully.');return true;}catch(e){setError(e instanceof Error?e.message:'Unable to save.');return false;}finally{setBusy(false);}}
 async function check(action:string){setBusy(true);setError('');try{await act({action,fix:await gps()});}catch(e){setError(e instanceof Error?e.message:'Location failed.');}finally{setBusy(false);}}
 const form=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget).entries());};
 const input=(label:string,name:string,type='text',value?:string|number,required=true)=><label className="field">{label}<input name={name} type={type} defaultValue={value} required={required} step={type==='number'?'any':undefined}/></label>;
 const submit=(text:string)=><button className="button" disabled={busy}>{busy?'Saving…':text}</button>;
 const name=(id:string)=>data?.people.find(p=>p.id===id)?.name||id;
 if(!data)return <section className="panel workforce"><p role={error?'alert':'status'}>{error||'Loading attendance and leave…'}</p><button className="button secondary" onClick={()=>load().catch(e=>setError(e.message))}>Retry</button></section>;
 const mine=data.profiles.find(p=>p.employee===me.id),today=data.entries.find(e=>e.kind==='daily'&&e.employee===me.id&&e.date===currentDate());
 const sections=['My day','Leave & requests','Attendance history',...(me.role!=='Employee'?['Review requests']:[]),...(data.payrollAccess?['Payroll']:[]),...(me.role==='Admin'?['Employee settings','Company setup','Sheets & audit']:[])];
 return <div className="workforce"><nav className="workforce-tabs" aria-label="Attendance and leave sections">{sections.map(s=><button key={s} className={'button '+(section===s?'':'secondary')} onClick={()=>{setSection(s);setError('');setSuccess('');}}>{s}</button>)}</nav>{error&&<p role="alert" className="workforce-error">{error}</p>}{success&&<p role="status" className="workforce-success">{success}</p>}
 {section==='My day'&&<><section className="panel workforce-card"><p className="eyebrow">INDIA STANDARD TIME · {currentDate()}</p><h2>{me.name} · {mine?.department==='Other'?mine.other:mine?.department||'Department not assigned'}</h2><p>Today: <b>{today?.data.status||'Not recorded'}</b>{today?.data.incomplete?' · Incomplete — review required':''}{today?.data.endDay?' · Day ended':''}</p><p>{({field:'Tap Start trip in Travel log: your phone’s current GPS location becomes the trip start and marks you Present. Stop each trip to record the end point. You can make several trips and visit several branches before End Day.',driver:'Start your trip at the office: Start trip in Travel log works only when GPS confirms you are inside the office geofence, and that start marks you Present. Stop the trip to record the end point.',office:'Check in and out inside the configured office geofence. Both GPS-confirmed check-in and check-out are required for Present attendance.'} as const)[tripUi(mine?.department).mode]}</p><p>Working hours: {data.policy.start}–{data.policy.end} IST. GPS is requested only for attendance actions or during active trips.</p><div className="actions">{tripUi(mine?.department).officeCheckInOut&&<><button className="button" disabled={busy||!!today?.data.checkIn} onClick={()=>check('checkIn')}>Office check-in</button><button className="button secondary" disabled={busy||!today?.data.checkIn||!!today?.data.checkOut} onClick={()=>check('checkOut')}>Office check-out</button></>}<button className="button secondary" disabled={busy||!today||!!today.data.endDay} onClick={()=>act({action:'endDay'})}>End Day</button></div><p className="detail-note">GPS errors can be submitted for review below. Browser tracking may pause when the screen locks. Keep the app open during trips; no reliable background tracking is claimed.</p></section><section className="panel workforce-card"><h2>Annual leave balances · {currentDate().slice(0,4)}</h2>{!data.policy.leaveTypes.length&&<p>Admin has not configured leave types or entitlements.</p>}{data.policy.leaveTypes.map(t=>{const leaves=data.entries.filter(e=>e.kind==='leave'&&e.employee===me.id&&e.date.startsWith(currentDate().slice(0,4))&&e.data.type===t.name);const used=leaves.filter(e=>e.data.status==='Approved').reduce((s,e)=>s+e.data.days.length,0),pending=leaves.filter(e=>e.data.status==='Pending').reduce((s,e)=>s+e.data.days.length,0);return <p key={t.name}><b>{t.name}</b> · {t.paid?'Paid':'Unpaid'} · Entitlement {t.annual} · Used {used} · Pending {pending} · Available {Math.max(0,t.annual-used-pending)}</p>;})}</section></>}
 {section==='Leave & requests'&&<div className="workforce-grid"><form className="panel workforce-card" onSubmit={e=>{const f=form(e);act({action:'requestLeave',...f});}}><h2>Request leave</h2><label className="field">Leave type<select name="type" required><option value="">Choose type</option>{data.policy.leaveTypes.map(t=><option key={t.name}>{t.name}</option>)}</select></label>{input('From','from','date',currentDate())}{input('To','to','date',currentDate())}{input('Reason','reason')}{submit('Submit leave request')}</form><form className="panel workforce-card" onSubmit={e=>{const f=form(e);act({action:'requestException',...f});}}><h2>Attendance exception</h2><p>Use this for failed GPS, missed checkout or an incomplete trip. Review never fabricates GPS evidence.</p>{input('Date','date','date',currentDate())}<label className="field">Requested attendance<select name="requested"><option>Present</option><option>Absent</option></select></label>{input('Reason and supporting details','reason')}{submit('Request review')}</form><form className="panel workforce-card" onSubmit={e=>{const f=form(e);act({action:'requestOvertime',...f});}}><h2>Request overtime approval</h2><p>Hours are calculated from completed GPS-verified records after 6:30 PM. An Admin or your Manager may approve them.</p>{input('Work date','date','date',currentDate())}{input('Reason','reason')}{submit('Submit verified overtime')}</form><section className="panel workforce-card"><h2>My requests</h2>{data.entries.filter(e=>['leave','exception','overtime'].includes(e.kind)&&e.employee===me.id).map(e=><article className="workforce-record" key={e.id}><b>{e.kind} · {e.date}{e.data.to?' to '+e.data.to:''}</b><p>{e.data.type||e.data.requested||`${e.data.hours} hours`} · {e.data.status}</p><p>{e.data.reason}</p>{e.data.reviewReason&&<p>Review: {e.data.reviewReason}</p>}</article>)}{!data.entries.some(e=>['leave','exception','overtime'].includes(e.kind)&&e.employee===me.id)&&<p>No requests yet.</p>}</section></div>}
 {section==='Attendance history'&&<section className="panel workforce-card"><h2>Daily attendance</h2><p>Absent is generated after the workday ends and open records are reconciled. Approved leave appears as Absent in the summary.</p><div className="workforce-scroll"><table><thead><tr><th>Date</th><th>Employee</th><th>Status</th><th>Review</th><th>Overtime hours</th></tr></thead><tbody>{data.entries.filter(e=>e.kind==='daily').map(e=><tr key={e.id}><td>{e.date}</td><td>{name(e.employee)}</td><td>{e.data.status}</td><td>{e.data.incomplete?'Incomplete':e.data.reconciled?'Reconciled':'Pending'}{e.data.exception?' · Exception reviewed':''}</td><td>{e.data.verifiedOvertimeHours||0}</td></tr>)}</tbody></table></div>{!data.entries.some(e=>e.kind==='daily')&&<p>No attendance records yet.</p>}{me.role==='Admin'&&<form onSubmit={e=>{const f=form(e);act({action:'reconcile',...f});}}><h3>Reconcile working days</h3><div className="form-row">{input('From','from','date',currentDate())}{input('To','to','date',currentDate())}</div>{submit('Reconcile attendance')}</form>}</section>}
 {section==='Review requests'&&<section className="panel workforce-card"><h2>Requests awaiting one approval</h2><p>Either an Admin or the employee’s team Manager can approve. Managers cannot approve their own requests.</p>{data.entries.filter(e=>['leave','exception','overtime'].includes(e.kind)&&e.data.status==='Pending'&&canReview(me,data.people.find(p=>p.id===e.employee)||{id:'',role:'',team:null})).map(e=><form key={e.id} className="workforce-record" onSubmit={ev=>{const f=form(ev);act({action:'review',id:e.id,...f});}}><h3>{name(e.employee)} · {e.kind} · {e.date}</h3><p>{e.data.reason}</p><p>{e.data.type||e.data.requested||`${e.data.hours} verified hours`}{e.data.to?' through '+e.data.to:''}</p><label className="field">Decision<select name="status"><option>Approved</option><option>Rejected</option></select></label>{input('Review reason','reason')}{submit('Save decision')}</form>)}{!data.entries.some(e=>['leave','exception','overtime'].includes(e.kind)&&e.data.status==='Pending')&&<p>No pending requests.</p>}</section>}
 {section==='Payroll'&&<section className="panel workforce-card"><h2>Monthly payroll · restricted</h2><p>Reconcile all working days and resolve incomplete records first. Missing salary or rate inputs remain uncalculated.</p><form onSubmit={e=>{const f=form(e);act({action:'payroll',...f});}}>{input('Month','month','month',currentDate().slice(0,7))}{submit('Calculate payroll')}</form>{data.entries.filter(e=>e.kind==='payroll').map(e=><article className="workforce-record" key={e.id}><h3>{name(e.employee)} · {e.date}</h3><p>Salary: {e.data.salary??'Not configured'} · Divisor: {e.data.divisor??'Not configured'} · Unpaid days: {e.data.unpaidDays}</p><p>LOP: {e.data.lop??'Not calculated'} · Approved overtime: {e.data.hours} hours · Rate: {e.data.rate??'Not configured'} · Multiplier: {e.data.multiplier??'Not configured'} · Overtime payable: {e.data.overtime??'Not calculated'}</p><p>{e.data.formula}</p></article>)}</section>}
 {section==='Employee settings'&&<><section className="panel workforce-card"><h2>Department and salary settings</h2><label className="field">Employee<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose employee</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.role}</option>)}</select></label>{chosen&&<ProfileForm key={chosen+JSON.stringify(data.profiles)} value={data.profiles.find(p=>p.employee===chosen)} busy={busy} save={p=>act({action:'profile',employee:chosen,profile:p})}/>}</section><form className="panel workforce-card" onSubmit={e=>{const f=form(e);act({action:'addEmployee',...f});}}><h2>Add an active employee</h2>{input('Full name','name')}{input('Indian mobile number','phone','tel')}{input('Initial password (8+ characters, letters and numbers)','password','password')}<label className="field">Role<select name="role"><option>Employee</option><option>Manager</option></select></label>{input('Manager access team (separate from department)','team')}{submit('Add employee')}</form></>}
 {section==='Company setup'&&<PolicyForm value={data.policy} busy={busy} save={p=>act({action:'policy',policy:p,confirm:true})}/>}
 {section==='Sheets & audit'&&<><section className="panel workforce-card"><h2>Google Sheets sync</h2><p>App-managed reports ? database is the source of truth</p><p><b>{data.sync?.configured?'Credentials configured — live verification required':'Live sync inactive — server secrets are missing'}</b></p><p>Admins and Managers: Viewer access with copying and downloads enabled. Employees must not have spreadsheet access. Owners retain permission controls; protections and hidden tabs do not provide privacy.</p>{data.sync?.alert&&<p role="alert">Last discrepancy: {data.sync.alert.tab} ? {data.sync.alert.message} ({new Date(data.sync.alert.detected).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST)</p>}<p>Last status: {data.sync?.status||'Not synced'}</p>{data.sync?.error&&<p role="alert">{data.sync.error}</p>}{data.sync?.finished&&<p>{new Date(data.sync.finished).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>}<p>Reconcile attendance and recalculate payroll before syncing. Retries replace the managed report rows without appending duplicates. Setup instructions are in WORKFORCE-SETUP.md.</p><button disabled={busy} className="button" onClick={()=>act({action:'sync'})}>Sync / retry reports</button></section><section className="panel workforce-card"><h2>Audit trail · latest 50 changes</h2>{data.audit.map((a,i)=><article className="workforce-record" key={i}><b>{a.action}</b><p>{name(a.actor)} · {new Date(a.created).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p><details><summary>Details</summary><pre>{a.details}</pre></details></article>)}</section></>}
 </div>;
}
function ProfileForm({value,busy,save}:{value?:Partial<Profile>;busy:boolean;save:(p:Profile)=>Promise<boolean>}){
 const [department,setDepartment]=useState(value?.department||'Other');
 return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const num=(key:string)=>f.get(key)===''?null:Number(f.get(key));save({department,other:String(f.get('other')||''),salary:num('salary'),divisor:num('divisor'),otRate:num('otRate'),otMultiplier:num('otMultiplier'),payrollAccess:f.get('payrollAccess')==='on'});}}><label className="field">Department<select value={department} onChange={e=>setDepartment(e.target.value as Profile['department'])}>{departments.map(d=><option key={d}>{d}</option>)}</select></label>{department==='Other'&&<label className="field">Department name<input name="other" required defaultValue={value?.other}/></label>}<div className="workforce-grid">{[['salary','Monthly salary (INR)'],['divisor','Monthly working-day divisor'],['otRate','Overtime hourly rate (INR)'],['otMultiplier','Overtime multiplier']].map(([key,label])=><label className="field" key={key}>{label}<input name={key} type="number" step="any" min={key==='divisor'||key==='otMultiplier'?0.01:0} defaultValue={String(value?.[key as keyof Profile]??'')} placeholder="Not configured"/></label>)}</div><label className="consent"><input type="checkbox" name="payrollAccess" defaultChecked={value?.payrollAccess}/> Explicit payroll access if this employee is a Manager</label><button className="button" disabled={busy}>Save employee settings</button></form>;
}
function PolicyForm({value,busy,save}:{value:Policy;busy:boolean;save:(p:Policy)=>Promise<boolean>}){
 const [holidays,setHolidays]=useState(value.holidays.map(h=>`${h.date},${h.name},${h.working?'working':'holiday'}`).join('\n')),[error,setError]=useState('');
 return <form className="panel workforce-card" onSubmit={e=>{e.preventDefault();setError('');try{const f=new FormData(e.currentTarget),str=(k:string)=>String(f.get(k)||'');const lines=(s:string)=>s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const p:Policy={office:str('lat')&&str('lng')?{lat:Number(str('lat')),lng:Number(str('lng')),radius:Number(str('radius')),maxAccuracy:Number(str('accuracy'))}:null,start:str('start'),end:str('end'),workdays:f.getAll('workday').map(Number),confirmedYears:str('years').split(',').map(Number),holidays:lines(holidays).map(line=>{const [date,name,kind]=line.split(',').map(s=>s.trim());if(!date||!name||!['working','holiday'].includes(kind))throw Error('Holiday rows must be date,name,holiday or date,name,working.');return {date,name,working:kind==='working'};}),leaveTypes:lines(str('leaveTypes')).map(line=>{const [name,paid,annual]=line.split(',').map(s=>s.trim());if(!name||!['paid','unpaid'].includes(paid)||annual==='')throw Error('Leave rows must be name,paid or unpaid,annual days.');return {name,paid:paid==='paid',annual:Number(annual)};})};save(p);}catch(e){setError(e instanceof Error?e.message:'Check the configuration.');}}}>
 <h2>Office, work calendar and leave policy</h2><p>No holidays, workdays or financial policy are assumed. Configure and confirm the calendar for each year.</p>{error&&<p role="alert">{error}</p>}<div className="workforce-grid">{[['lat','Office latitude',value.office?.lat],['lng','Office longitude',value.office?.lng],['radius','Geofence radius (metres)',value.office?.radius],['accuracy','Maximum GPS accuracy (metres, up to 100)',value.office?.maxAccuracy]].map(([key,label,v])=><label className="field" key={String(key)}>{label}<input name={String(key)} type="number" step="any" defaultValue={v??''}/></label>)}</div><div className="form-row"><label className="field">Start (IST)<input required type="time" name="start" defaultValue={value.start}/></label><label className="field">End (IST)<input required type="time" name="end" defaultValue={value.end}/></label></div><fieldset><legend>Working days</legend><div className="actions">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=><label key={d}><input type="checkbox" name="workday" value={i} defaultChecked={value.workdays.includes(i)}/> {d}</label>)}</div></fieldset><label className="field">Holiday calendar (one line: YYYY-MM-DD,name,holiday or working)<textarea rows={7} value={holidays} onChange={e=>setHolidays(e.target.value)} placeholder="Enter the confirmed company calendar"/></label><label className="field">Import calendar CSV (same format, no header)<input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f)setHolidays(await f.text());}}/></label><label className="field">Confirmed calendar years (comma separated)<input required name="years" defaultValue={value.confirmedYears.join(',')} placeholder="e.g. 2026"/></label><label className="field">Leave types (one line: name,paid or unpaid,annual days)<textarea name="leaveTypes" rows={5} defaultValue={value.leaveTypes.map(t=>`${t.name},${t.paid?'paid':'unpaid'},${t.annual}`).join('\n')}/></label><label className="consent"><input required type="checkbox"/> I confirm that these are the company’s approved holidays, working-day overrides and leave rules for the listed years.</label><button disabled={busy} className="button">Save confirmed company policy</button></form>;
}
